[package]
name = "conerobo"
version = "0.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
csv = "1.1"
rand = "0.8.5"

[profile.release]
opt-level = 3

[profile.dev]
opt-level = 1
