[package]
name = "conerobo_tracker"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bindings = {path = "bindings"}
windows = "0.18.0"
fltk = "1.1.12"

[profile.release]
opt-level = 3

[profile.dev]
opt-level = 2
