config:
  Container:
    styles:
      border: &border-style "[#002090]{item}"
      corner: *border-style

  Window:
    styles:
      border: *border-style
      corner: *border-style

  Splitter:
    styles:
      separator: *border-style

widgets:
  MainWindow:
    type: Window
    width: 80
    height: 32
    box: DOUBLE
    widgets:
      # Hello world splitter
      - Splitter:
          widgets:
            - Label:
                value: "[228]Hello"
            - Label:
                value: "< [72]World[/] >"